### ISSUE TITLE
Do you have an idea for a small, self-contained InterMine project? GSoC might be for you!

### ISSUE THREAD

**Issue by yochannah** [intermine/outreach#5]
If you've always thought "Gee, I wish 'x' feature" existed in InterMine", or perhaps "That's a neat idea but I don't have time to do it", consider proposing it here so we can add it to our GSoC project list.

- ideas need to be small enough they can be implemented in ~8 weeks
- the project has to be InterMine related - using the API or working on a core InterMine repo in some way
- please add whether or not you'd be willing to mentor a student while they are doing this project.
- share with your friends!

If you'd rather not make a ticket, you can always [contact us](http://intermine.readthedocs.io/en/latest/about/contact-us/) with your idea instead and we can talk it through with you and add it on your behalf.

**Comment by julie-sullivan** [comment]
What's an example project? Do we have the list of our previous ones? Might help give an idea of scope etc.

**Comment by julie-sullivan** [comment]
I know that JavaScript tools are all the rage! Didn't Sam's group develop a synteny viewer for their GSoC? We have lots of tool ideas (data browser, heatmaps etc) Would there be enough JavaScript interest from students do you think? Does anyone use JavaScript anymore. ;p

**Comment by yochannah** [comment]
Good idea Julie! Some previous examples of projects include:

- an [iOS app for InterMine](https://joystate.github.io/intermine-ios/)
- exploring [using Neo4j as a backend for InterMine](http://yasharmaster.github.io/blog/2017/gsoc-2017-final-report/)
- using [machine learning to identify InterMine objects that are similar to one another](https://samyadeepblog.wordpress.com/2017/07/03/first-blog-post/).
- creating a [registry ofcommunity InterMines](http://registry.intermine.org/)
- Completing InterMine's R client, [InterMineR](https://bioconductor.org/packages/release/bioc/html/InterMineR.html)

or you can read more on our blog: https://intermineorg.wordpress.com/2017/05/04/gsocers-assemble-announcing-the-intermine-gsoc-2017-students/ 

@julie-sullivan re javascript, I think there should be plenty of interest! there were around 240 GSoC projects (from all GSoC organisations, not just InterMine) that mention javascript over 2016-2017: https://summerofcode.withgoogle.com/archive/search/?q=javascript

**Comment by yochannah** [comment]
**FINAL CALL FOR PROJECT IDEAS** Please add your project ideas by the end of this week - (December 14). Feel free to discuss project items here, or add them directly to the list.

Project idea list: https://docs.google.com/document/d/1KGiGuP5rO5lJQhDwjyqv5u1CyhiDZRgZhjDRwsr_MBw/edit#

**Comment by yochannah** [comment]
GSoC org applications close on the 23rd of Jan, and we'll hear if we're accepted by Feb 12. 

It's still possible to add items to the list, but please do so by discussing with the team or PRing [this repo](https://github.com/intermine/gsoc/blob/master/project-ideas/2018.md)

http://intermine.org/gsoc/project-ideas/2018/

**Comment by yochannah** [comment]
we're live in gsoc so I'm closing this issue
